### ISSUE TITLE
Could you update the version of this gem on rubygems.org?

### ISSUE THREAD

**Issue by s0ph0s-dog** [bhaberer/cinch-cooldown#7]
[rubygems.org](https://rubygems.org/gems/cinch-cooldown) seems to have the previous version of this gem marked as current. Are you responsible for updating that, and if so, could you push the v1.2.0 code changes?  

Thanks!

**Comment by s0ph0s-2** [comment]
Any updates?

**Comment by bhaberer** [comment]
Oh, strange, not sure how I missed this! I'll push the changes once I get
home from work, not sure why they aren't up already.

**Comment by s0ph0s-2** [comment]
Awesome, thanks!

**Comment by rikai** [comment]
Good to hear! Can't wait to finally implement this! 👍

**Comment by rikai** [comment]
Did you get a chance to do this? :)

**Comment by s0ph0s-2** [comment]
Thanks! Things are working great now.
